#!/bin/bash
source ./my_password

# Running docker container list (w/ name)
ContainerList=$(echo $rootPw | sudo docker ps --format json | jq -r '.Names')
printf %s\\n ${ContainerList} | printf %s "$(cat)"|jq -R -s 'split("\n")'

